###
POST http://localhost:8000/compress
Content-Type: application/json

{
	"text": "Before we go any further, we’ll need a urine sample. Glass of water, Madam. You'll be pleased to know your parents have been fully vetted, though that father is a cross to bear, isn't he? Your mother is a breath of fresh air."
}

### Checing for single node
POST http://localhost:8000/compress
Content-Type: application/json

{
  "text": "dddddd"
}

###
POST http://localhost:8000/decompress
Content-Type:  application/json

{
  "codes": {
    "huffman_codes": [
      {
        "character": "d",
        "frequency": 6,
        "huffman_code": "0"
      }
    ]
  },
  "tree": {
    "Leaf": {
      "freq": 6,
      "value": "d"
    }
  },
  "encoded_text": "000000"
}